### ISSUE TITLE
Invalid plugin.yml ERROR

### ISSUE THREAD

**Issue by Tikkle** [2LStudios-MC/AntiBot#11]
Dragged and dropped it into my server, started my server, this was spewed 10 lines into a startup.

This was on the latest AntiBot download (0.5.1)

The server is running Paper version git-Paper-281 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

Let me know if you need any more info :)

```[00:12:02] [Server thread/ERROR]: Could not load 'plugins\AntiBot-0.5.1.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:161) ~[patched_1.15.2.jar:git-Paper-281]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.15.2.jar:git-Paper-281]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-281]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-281]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:897) ~[patched_1.15.2.jar:git-Paper-281]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
	... 6 more```

**Comment by Tikkle** [comment]
It's been three days and no support? Hello?

**Comment by linsaftw** [comment]
The plugin is for BungeeCord.
